export const projectCardInfo = [
    { id: 1, title: 'Computer Vision Stat Extractor', description: 'Extracted real world positional data of soccer players from broadcast footage. Included the construction of homography and data analysis.', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'stat_extractor' }, // https://github.com/rhit-waterblt/csse461-project-soccer
    { id: 2, title: 'Soccer Database and Interface', description: 'Developed MSSQL Database with Triggers, Indices, and Stored Procedures while ensuring full SQL injection protection on backend and java frontend', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'soccer_database' }, //https://github.com/RHIT-CSSE333/courseproject-s3g7
    { id: 3, title: 'Deep Learning GeoImaging', description: 'Trained and fine-tuned neural network to classify images into their predicted country of origin. Includes extensive research and exploration', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'geoguesser' }, // See pdf
    { id: 4, title: 'Fruit Detector', description: 'Utilized color spaces and morphology to automatically detect and classify fruit in images.', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'fruit_finder' },
    { id: 5, title: 'Test Driven Design', description: 'Developed and maintained Super Auto Pets game following Test Driven Design', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'tdd' }, //https://github.com/rhit-csse376/2022S-Team8-SuperAutoPets
    { id: 6, title: 'Java Linter', description: 'Utilized the ASM library to develope a java linter capable of detecting software design patterns and bad practices in code.', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'linter' }, //https://github.com/rhit-csse374/project202320-s1s2-team07
    { id: 7, title: 'Scheme/Racket Interpreter', description: 'Developed an interpreter for racket to learn functional programming, closures/environents, and continuations.', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'interpreter' }, // have file but not repo yet
    { id: 8, title: 'Analysis of APR in NCAA Sports', description: 'Processed and analyzed the performances of university and program Academic Progress Rates with respect to sport and gender.', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'data_mining' }, // See pdf
    { id: 9, title: 'Full Stack Web/Mobile Application', description: 'Developed project for posting and bidding local small scale contracting work. Built Flask API with token authorization served with AWS Lambda. Includes React Native frontend, Firebase Authentication ', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'landscape' }, // Private repos
    { id: 10, title: '16 Bit Accumulator Processor', description: 'Designed and implemented a CPU datapath with a custom machine code instruction set and assembler.', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'processor' }, // https://github.com/rhit-csse232/rhit-csse232-2122b-project-baratheon-2122b
    { id: 11, title: 'TODO - Soccer Wordler', description: 'Description for Project 10', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'url_to_project10' },
    { id: 12, title: 'TODO - Soccer player and line detection', description: 'Description for Project 11', imageUrl: process.env.PUBLIC_URL + '/ProjectImage.png', projectUrl: 'url_to_project11' }
];